import './globals.css';
import { Open_Sans } from 'next/font/google';
import Header from '@/components/Header';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import { NextAuthProvider } from '@/context/NextAuthProvider';
import { SWRConfig } from 'swr';
import SWRConfigContext from '@/context/SWRConfigContext';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${sans.className} max-w-screen-2xl flex flex-col m-auto`}
      >
        <NextAuthProvider>
          <header className="border-b border-gray-300">
            <Header />
          </header>
          <main>
            <SWRConfigContext>{children}</SWRConfigContext>
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
