import './globals.css';
import { Open_Sans } from 'next/font/google';
import Header from '@/components/Header';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import { NextAuthProvider } from '@/context/NextAuthProvider';
import { SWRConfig } from 'swr';
import SWRConfigContext from '@/context/SWRConfigContext';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${sans.className} bg-neutral-50 w-full`}>
        <NextAuthProvider>
          <header className="bg-white border-b sticky top-0 z-10">
            <div className="max-w-screen-2xl mx-auto">
              <Header />
            </div>
          </header>
          <main className="w-full flex justify-center mx-auto max-w-screen-xl">
            <SWRConfigContext>{children}</SWRConfigContext>
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
