import './globals.css';
import { Open_Sans } from 'next/font/google';
import Header from '@/components/Header';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
